# Eigenvalue Problem

Assume we have a transformation matrix $A$, then we are looking for an vector $v$ such that

$A\vec{v} = \lambda \vec{v}$, where $\lambda$ is a scalar

$\lambda$ is the eigen value and $\vec{v}$ is the eigen vector

Concreteley we are looking for $\lambda$ such that the transformation matrix $A$ only has a scaling effect, but no rotation effect on $v$

so given $A\vec{v} = \lambda \vec{v}$ , if we subtract $A\vec{v}$ from both sides we get 

$\vec{0} = \lambda\vec{v} - A\vec{v}$ and 

$ \vec{v} (\lambda I_n - A) = \vec{0}$

For $(\lambda I_n - A)$ to be non-trivial $\vec{v}$ must belong to the nullspace of $(\lambda I_n - A)$

That is to say $\vec{v} \subset N(\lambda I_n - A)$ where $N(x)$ denotes the nullspace

**Linearity Property**
If a matrix $D$ is non-trivial then it has dependent columns and therefore $D$ is not invertible and $\mid{D}\mid = \vec{0}$

From this it follows that $\mid{\lambda I_n - A}\mid = \vec{0}$

So for a transformation matrix $A$ we are looking for a vector $\vec{v}$ and a scalar $\lambda$  such that $\mid{\lambda I_n - A}\mid = \vec{0}$ and $A\vec{v} = \lambda \vec{v}$

If we solve for $\lambda_i$, we have found the eigen values of transformation $A$,

we can then solve for the vectors $\vec{v}_i$ to find the eigen vector of $A$

**Pseudocode**

Inputs: 
    $A$
    
Begin:
    
solve for  $\lambda$ from $\mid{\lambda I_n - A}\mid = \vec{0}$
    
for each $\lambda_i$ in $\lambda$:

   find $\vec{v}$ such that $ \vec{v} (\lambda I_n - A) = \vec{0}$
   
End:



# EVD of Covariance Matrices

Given the covariance matrix $\mathbf{\Sigma}$

$\mathbf{\Sigma} = {\sum}_i^D\lambda_i u_i u_i^T$ we can assert that $\mathbf{\Sigma}=VDV^{-1}$

Since the covariance matrix is symmetric, it has the propterty that all of its eigen vectors are not only independent but also orthogonal

Let $A$ be the covariance matrix
Let $V = [v_i v_2 ...... v_n]$ be a matrix of eigen vectors placed in the columns
Let $D$ be a diagonal matrix where the $ii^{th}$ position, then in accordance to the eigen value problem 

$AV = VD$
$AV = [Av_i, Av_2, ....., Av_n ]$

$VD = [\lambda_1 v_i, \lambda_1 v_2, ....., \lambda_n v_n ]$

Since $\mathbf{\Sigma}$ is symmetric, if we choose any two eigen values, $\lambda_1 , \lambda_2$ and corresponding eigen vectors, $v_1, v_2$

then $\lambda_1 v_1 v_2$ = $(\lambda_1 v_1)^T v_2$

$=(A v_1)^T$

$=v_1^TA^Tv_2$

$=v_1^T(Av_2)$

$=v_1^T(\lambda_2 v_2)$

So $\lambda_1 v_1 v_2$ = $\lambda_2 v_1 v_2$

and it follows that 

$(\lambda_1 - \lambda_2)v_1 . v_2 = 0$

Satisfying the condition of no dependence in the columns of a symmetric matrix, therefore we can say that the eigen vectors of a symmetric matrix are orthogonal

If $V$ is an orthogonal matrix then it follows that $V^T = V^{-1}$

Then the covariance matrix $\mathbf{\Sigma}$ which is a symmetric matrix can be diagonalized by a diagonal matrix $D$ and the matrix of eigen vectors $V$ such that

$\mathbf{\Sigma}$ = $VDV^{-1}$

Since $\mathbf{\Sigma}^T = \mathbf{\Sigma}$

$\mathbf{\Sigma}^T = (VDV^T)^T = V^{TT}D^TV^T = VDV^T = \mathbf{\Sigma}$


# PCA using EVD

In [12]:
import numpy as np

In [81]:
N = 3

In [82]:
input_matrix = np.random.randint(10,size=(N, N)).astype(np.float)
input_matrix

array([[6., 9., 7.],
       [6., 7., 1.],
       [0., 7., 7.]])

In [83]:
mn = input_matrix.mean(axis = 0)
mn

array([4.        , 7.66666667, 5.        ])

In [84]:
# Whiten the data

input_matrix = input_matrix - mn
input_matrix

array([[ 2.        ,  1.33333333,  2.        ],
       [ 2.        , -0.66666667, -4.        ],
       [-4.        , -0.66666667,  2.        ]])

In [85]:
covariance = np.cov(input_matrix)
covariance

array([[ 0.14814815, -0.07407407, -0.07407407],
       [-0.07407407,  9.03703704, -8.96296296],
       [-0.07407407, -8.96296296,  9.03703704]])

In [86]:
values, vectors = np.linalg.eig(covariance)
vectors,values

(array([[ 8.16496581e-01, -5.77350269e-01, -4.68396749e-19],
        [-4.08248290e-01, -5.77350269e-01, -7.07106781e-01],
        [-4.08248290e-01, -5.77350269e-01,  7.07106781e-01]]),
 array([ 2.22222222e-01, -6.38378239e-16,  1.80000000e+01]))

In [87]:
values, vectors = np.linalg.eig(input_matrix)
vectors,values

(array([[ 0.21516574-0.14272481j,  0.21516574+0.14272481j,
         -0.30151134+0.j        ],
        [-0.77459667+0.j        , -0.77459667-0.j        ,
          0.90453403+0.j        ],
        [ 0.55943093+0.14272481j,  0.55943093-0.14272481j,
         -0.30151134+0.j        ]]),
 array([ 1.66666667e+00+1.1055416j,  1.66666667e+00-1.1055416j,
        -2.64283063e-15+0.j       ]))

Evaluate ${\Sigma v = \lambda v}$

${\Sigma v}$

In [88]:
for i in range(len(N)):
    eigv = vectors[:,i].reshape(1,N).T
    np.testing.assert_array_almost_equal(scatter_matrix.dot(eigv), eig_val_sc[i] * eigv,
                                         decimal=6, err_msg='', verbose=True)

TypeError: object of type 'int' has no len()

 ${\lambda v}$

array([[-9.31048723e+00, -1.57001466e-16, -3.55656026e-03],
       [ 6.32600563e+00, -1.57001466e-16, -1.30861838e-02],
       [ 2.98448160e+00, -1.57001466e-16,  1.66427440e-02]])