# Eigenvalue Problem

Assume we have a transformation matrix $A$, then we are looking for an vector $v$ such that

$A\vec{v} = \lambda \vec{v}$, where $\lambda$ is a scalar

$\lambda$ is the eigen value and $\vec{v}$ is the eigen vector

Concreteley we are looking for $\lambda$ such that the transformation matrix $A$ only has a scaling effect, but no rotation effect on $v$

so given $A\vec{v} = \lambda \vec{v}$ , if we subtract $A\vec{v}$ from both sides we get 

$\vec{0} = \lambda\vec{v} - A\vec{v}$ and 

$ \vec{v} (\lambda I_n - A) = \vec{0}$

For $(\lambda I_n - A)$ to be non-trivial $\vec{v}$ must belong to the nullspace of $(\lambda I_n - A)$

That is to say $\vec{v} \subset N(\lambda I_n - A)$ where $N(x)$ denotes the nullspace

**Linearity Property**
If a matrix $D$ is non-trivial then it has dependent columns and therefore $D$ is not invertible and $\mid{D}\mid = \vec{0}$

From this it follows that $\mid{\lambda I_n - A}\mid = \vec{0}$

So for a transformation matrix $A$ we are looking for a vector $\vec{v}$ and a scalar $\lambda$  such that $\mid{\lambda I_n - A}\mid = \vec{0}$ and $A\vec{v} = \lambda \vec{v}$

If we solve for $\lambda_i$, we have found the eigen values of transformation $A$,

we can then solve for the vectors $\vec{v}_i$ to find the eigen vector of $A$

**Pseudocode**

Inputs: 
    $A$
    
Begin:
    
solve for  $\lambda$ from $\mid{\lambda I_n - A}\mid = \vec{0}$
    
for each $\lambda_i$ in $\lambda$:

   find $\vec{v}$ such that $ \vec{v} (\lambda I_n - A) = \vec{0}$
   
End:



# EVD of Covariance Matrices

Given the covariance matrix $\mathbf{\Sigma}$

$\mathbf{\Sigma} = {\sum}_i^D\lambda_i u_i u_i^T$ we can assert that $\mathbf{\Sigma}=VDV^{-1}$

Since the covariance matrix is symmetric, it has the propterty that all of its eigen vectors are not only independent but also orthogonal

Let $A$ be the covariance matrix
Let $V = [v_i v_2 ...... v_n]$ be a matrix of eigen vectors placed in the columns
Let $D$ be a diagonal matrix where the $ii^{th}$ position, then in accordance to the eigen value problem 

$AV = VD$
$AV = [Av_i, Av_2, ....., Av_n ]$

$VD = [\lambda_1 v_i, \lambda_1 v_2, ....., \lambda_n v_n ]$

Since $\mathbf{\Sigma}$ is symmetric, if we choose any two eigen values, $\lambda_1 , \lambda_2$ and corresponding eigen vectors, $v_1, v_2$

then $\lambda_1 v_1 v_2$ = $(\lambda_1 v_1)^T v_2$

$=(A v_1)^T$

$=v_1^TA^Tv_2$

$=v_1^T(Av_2)$

$=v_1^T(\lambda_2 v_2)$

So $\lambda_1 v_1 v_2$ = $\lambda_2 v_1 v_2$

and it follows that 

$(\lambda_1 - \lambda_2)v_1 . v_2 = 0$

Satisfying the condition of no dependence in the columns of a symmetric matrix, therefore we can say that the eigen vectors of a symmetric matrix are orthogonal

If $V$ is an orthogonal matrix then it follows that $V^T = V^{-1}$

Then the covariance matrix $\mathbf{\Sigma}$ which is a symmetric matrix can be diagonalized by a diagonal matrix $D$ and the matrix of eigen vectors $V$ such that

$\mathbf{\Sigma}$ = $VDV^{-1}$

Since $\mathbf{\Sigma}^T = \mathbf{\Sigma}$

$\mathbf{\Sigma}^T = (VDV^T)^T = V^{TT}D^TV^T = VDV^T = \mathbf{\Sigma}$


# PCA using EVD

In [1]:
import numpy as np

In [2]:
N = 3

In [3]:
input_matrix = np.random.randint(10,size=(N, 20)).astype(np.float)
input_matrix

array([[7., 4., 1., 9., 2., 8., 3., 2., 2., 0., 3., 6., 8., 5., 9., 6.,
        9., 3., 7., 3.],
       [6., 4., 4., 4., 6., 2., 2., 8., 3., 4., 3., 8., 2., 3., 6., 7.,
        0., 9., 2., 3.],
       [4., 1., 2., 9., 3., 8., 1., 3., 9., 6., 1., 9., 5., 9., 2., 0.,
        1., 1., 2., 1.]])

In [4]:
mn = input_matrix.mean(axis = 0)
mn

array([5.66666667, 3.        , 2.33333333, 7.33333333, 3.66666667,
       6.        , 2.        , 4.33333333, 4.66666667, 3.33333333,
       2.33333333, 7.66666667, 5.        , 5.66666667, 5.66666667,
       4.33333333, 3.33333333, 4.33333333, 3.66666667, 2.33333333])

In [5]:
# Whiten the data

input_matrix = input_matrix - mn
input_matrix

array([[ 1.33333333,  1.        , -1.33333333,  1.66666667, -1.66666667,
         2.        ,  1.        , -2.33333333, -2.66666667, -3.33333333,
         0.66666667, -1.66666667,  3.        , -0.66666667,  3.33333333,
         1.66666667,  5.66666667, -1.33333333,  3.33333333,  0.66666667],
       [ 0.33333333,  1.        ,  1.66666667, -3.33333333,  2.33333333,
        -4.        ,  0.        ,  3.66666667, -1.66666667,  0.66666667,
         0.66666667,  0.33333333, -3.        , -2.66666667,  0.33333333,
         2.66666667, -3.33333333,  4.66666667, -1.66666667,  0.66666667],
       [-1.66666667, -2.        , -0.33333333,  1.66666667, -0.66666667,
         2.        , -1.        , -1.33333333,  4.33333333,  2.66666667,
        -1.33333333,  1.33333333,  0.        ,  3.33333333, -3.66666667,
        -4.33333333, -2.33333333, -3.33333333, -1.66666667, -1.33333333]])

In [13]:
cov = 1/(N-1)*np.matmul(input_matrix,input_matrix.T)
cov

array([[ 55.38888889, -28.27777778, -27.11111111],
       [-28.27777778,  56.55555556, -28.27777778],
       [-27.11111111, -28.27777778,  55.38888889]])

In [12]:
covariance = np.cov(input_matrix)
covariance

array([[ 5.5494152 , -2.95847953, -2.59093567],
       [-2.95847953,  5.95204678, -2.99356725],
       [-2.59093567, -2.99356725,  5.58450292]])

In [14]:
lambdas, vs = np.linalg.eig(cov)
vectors,values

(array([[ 5.77350269e-01,  7.07106781e-01,  4.08248290e-01],
        [ 5.77350269e-01,  1.73979692e-15, -8.16496581e-01],
        [ 5.77350269e-01, -7.07106781e-01,  4.08248290e-01]]),
 array([ 0.        , 82.5       , 84.83333333]))

In [18]:
lambdas, vs = np.linalg.eig(covariance)
vectors,values

(array([[ 0.57735027,  0.72262852,  0.38009826],
        [ 0.57735027, -0.03213951, -0.81586379],
        [ 0.57735027, -0.69048901,  0.43576553]]),
 array([0.        , 8.1566977 , 8.92926721]))

Evaluate ${\Sigma v = \lambda v}$

${\Sigma v}$

In [16]:
sigma_v = np.matmul(covariance,vs)
sigma_v

array([[ 1.55431223e-15,  5.89426240e+00,  3.39399892e+00],
       [-6.66133815e-16, -2.62152291e-01, -7.28506576e+00],
       [ 0.00000000e+00, -5.63211011e+00,  3.89106684e+00]])

 ${\lambda v}$

In [20]:
lambda_v = lambdas*vectors
lambda_v

array([[ 0.        ,  5.8942624 ,  3.39399892],
       [ 0.        , -0.26215229, -7.28506576],
       [ 0.        , -5.63211011,  3.89106684]])