# Eigenvalue Problem

Assume we have a transformation matrix $A$, then we are looking for an vector $v$ such that

$A\vec{v} = \lambda \vec{v}$, where $\lambda$ is a scalar

$\lambda$ is the eigen value and $\vec{v}$ is the eigen vector

Concreteley we are looking for $\lambda$ such that the transformation matrix $A$ only has a scaling effect, but no rotation effect on $v$

so given $A\vec{v} = \lambda \vec{v}$ , if we subtract $A\vec{v}$ from both sides we get 

$\vec{0} = \lambda\vec{v} - A\vec{v}$ and 

$ \vec{v} (\lambda I_n - A) = \vec{0}$

For $(\lambda I_n - A)$ to be non-trivial $\vec{v}$ must belong to the nullspace of $(\lambda I_n - A)$

That is to say $\vec{v} \subset N(\lambda I_n - A)$ where $N(x)$ denotes the nullspace

**Linearity Property**
If a matrix $D$ is non-trivial then it has dependent columns and therefore $D$ is not invertible and $\mid{D}\mid = \vec{0}$

From this it follows that $\mid{\lambda I_n - A}\mid = \vec{0}$

So for a transformation matrix $A$ we are looking for a vector $\vec{v}$ and a scalar $\lambda$  such that $\mid{\lambda I_n - A}\mid = \vec{0}$ and $A\vec{v} = \lambda \vec{v}$

If we solve for $\lambda_i$, we have found the eigen values of transformation $A$,

we can then solve for the vectors $\vec{v}_i$ to find the eigen vector of $A$

**Pseudocode**

Inputs: 
    $A$
    
Begin:
    
solve for  $\lambda$ from $\mid{\lambda I_n - A}\mid = \vec{0}$
    
for each $\lambda_i$ in $\lambda$:

   find $\vec{v}$ such that $ \vec{v} (\lambda I_n - A) = \vec{0}$
   
End:



# EVD of Covariance Matrices

Given the covariance matrix $\mathbf{\Sigma}$

$\mathbf{\Sigma} = {\sum}_i^D\lambda_i u_i u_i^T$ we can assert that $\mathbf{\Sigma}=VDV^{-1}$

Since the covariance matrix is symmetric, it has the propterty that all of its eigen vectors are not only independent but also orthogonal

Let $A$ be the covariance matrix
Let $V = [v_i v_2 ...... v_n]$ be a matrix of eigen vectors placed in the columns
Let $D$ be a diagonal matrix where the $ii^{th}$ position, then in accordance to the eigen value problem 

$AV = VD$
$AV = [Av_i, Av_2, ....., Av_n ]$

$VD = [\lambda_1 v_i, \lambda_1 v_2, ....., \lambda_n v_n ]$

Since $\mathbf{\Sigma}$ is symmetric, if we choose any two eigen values, $\lambda_1 , \lambda_2$ and corresponding eigen vectors, $v_1, v_2$

then $\lambda_1 v_1 v_2$ = $(\lambda_1 v_1)^T v_2$

$=(A v_1)^T$

$=v_1^TA^Tv_2$

$=v_1^T(Av_2)$

$=v_1^T(\lambda_2 v_2)$

So $\lambda_1 v_1 v_2$ = $\lambda_2 v_1 v_2$

and it follows that 

$(\lambda_1 - \lambda_2)v_1 . v_2 = 0$

Satisfying the condition of no dependence in the columns of a symmetric matrix, therefore we can say that the eigen vectors of a symmetric matrix are orthogonal

If $V$ is an orthogonal matrix then it follows that $V^T = V^{-1}$

Then the covariance matrix $\mathbf{\Sigma}$ which is a symmetric matrix can be diagonalized by a diagonal matrix $D$ and the matrix of eigen vectors $V$ such that

$\mathbf{\Sigma}$ = $VDV^{-1}$

Since $\mathbf{\Sigma}^T = \mathbf{\Sigma}$

$\mathbf{\Sigma}^T = (VDV^T)^T = V^{TT}D^TV^T = VDV^T = \mathbf{\Sigma}$


# PCA using EVD

In [2]:
import numpy as np

In [3]:
N = 3

In [4]:
input_matrix = np.random.randint(10,size=(N, 20)).astype(np.float)
input_matrix

array([[0., 4., 6., 6., 3., 2., 1., 1., 3., 5., 4., 8., 3., 2., 9., 0.,
        2., 6., 1., 9.],
       [9., 3., 8., 8., 0., 2., 9., 0., 9., 6., 4., 1., 7., 7., 7., 3.,
        8., 0., 3., 6.],
       [0., 4., 2., 5., 4., 7., 1., 4., 7., 1., 8., 7., 1., 5., 1., 7.,
        7., 3., 0., 6.]])

In [5]:
mn = input_matrix.mean(axis = 0)
mn

array([3.        , 3.66666667, 5.33333333, 6.33333333, 2.33333333,
       3.66666667, 3.66666667, 1.66666667, 6.33333333, 4.        ,
       5.33333333, 5.33333333, 3.66666667, 4.66666667, 5.66666667,
       3.33333333, 5.66666667, 3.        , 1.33333333, 7.        ])

In [6]:
# Whiten the data

input_matrix = input_matrix - mn
input_matrix

array([[-3.        ,  0.33333333,  0.66666667, -0.33333333,  0.66666667,
        -1.66666667, -2.66666667, -0.66666667, -3.33333333,  1.        ,
        -1.33333333,  2.66666667, -0.66666667, -2.66666667,  3.33333333,
        -3.33333333, -3.66666667,  3.        , -0.33333333,  2.        ],
       [ 6.        , -0.66666667,  2.66666667,  1.66666667, -2.33333333,
        -1.66666667,  5.33333333, -1.66666667,  2.66666667,  2.        ,
        -1.33333333, -4.33333333,  3.33333333,  2.33333333,  1.33333333,
        -0.33333333,  2.33333333, -3.        ,  1.66666667, -1.        ],
       [-3.        ,  0.33333333, -3.33333333, -1.33333333,  1.66666667,
         3.33333333, -2.66666667,  2.33333333,  0.66666667, -3.        ,
         2.66666667,  1.66666667, -2.66666667,  0.33333333, -4.66666667,
         3.66666667,  1.33333333,  0.        , -1.33333333, -1.        ]])

**Scatter method for evaluating covariance**

In [7]:
cov = 1/(N-1)*np.matmul(input_matrix,input_matrix.T)
cov

array([[ 48.88888889, -34.27777778, -14.61111111],
       [-34.27777778,  77.05555556, -42.77777778],
       [-14.61111111, -42.77777778,  57.38888889]])

**Numpy implementation of covariance**

In [8]:
covariance = np.cov(input_matrix)
covariance

array([[ 4.88304094, -3.21345029, -1.66959064],
       [-3.21345029,  7.51900585, -4.30555556],
       [-1.66959064, -4.30555556,  5.9751462 ]])

It seems numpy method produces a matrix that is scaled down by a factor of circa 10 in this case 

In [9]:
lambdas_sc, vs_sc = np.linalg.eig(cov)
lambdas_sc, vs_sc

(array([1.42108547e-14, 6.66427892e+01, 1.16690544e+02]),
 array([[ 0.57735027,  0.75996351,  0.29853331],
        [ 0.57735027, -0.12144433, -0.80741436],
        [ 0.57735027, -0.63851918,  0.50888105]]))

In [10]:
lambdas, vs = np.linalg.eig(covariance)
lambdas, vs

(array([8.88178420e-16, 6.89463621e+00, 1.14825568e+01]),
 array([[-0.57735027, -0.77729957,  0.24994409],
        [-0.57735027,  0.17219185, -0.79813322],
        [-0.57735027,  0.60510772,  0.54818913]]))

## Testing EVD

Evaluate ${\Sigma v = \lambda v}$

${\Sigma v}$

In [11]:
sigma_v = np.matmul(covariance,vs)
sigma_v

array([[ 1.88737914e-15, -5.35919775e+00,  2.86999721e+00],
       [-4.44089210e-16,  1.18720018e+00, -9.16460998e+00],
       [-1.33226763e-15,  4.17199757e+00,  6.29461277e+00]])

 ${\lambda v}$

In [12]:
lambda_v = lambdas*vs
lambda_v

array([[-5.12790050e-16, -5.35919775e+00,  2.86999721e+00],
       [-5.12790050e-16,  1.18720018e+00, -9.16460998e+00],
       [-5.12790050e-16,  4.17199757e+00,  6.29461277e+00]])

As you can see with the exception rounding off for very low numbers, ${\Sigma v = \lambda v}$

## Testing EVD on alternate calculation for covariance

Evaluate ${\Sigma v = \lambda v}$

${\Sigma v}$

In [13]:
sigma_v = np.matmul(cov,vs_sc)
sigma_v

array([[ 0.00000000e+00,  5.06460878e+01,  3.48360139e+01],
       [ 3.55271368e-15, -8.09338865e+00, -9.42176206e+01],
       [ 7.10542736e-15, -4.25526991e+01,  5.93816066e+01]])

 ${\lambda v}$

In [14]:
lambda_v = lambdas_sc*vs_sc
lambda_v

array([[ 8.20464080e-15,  5.06460878e+01,  3.48360139e+01],
       [ 8.20464080e-15, -8.09338865e+00, -9.42176206e+01],
       [ 8.20464080e-15, -4.25526991e+01,  5.93816066e+01]])

Same result but it seems covariance matrix using $numpy$ produces a scaled down product by a factor of about 10 most entrie match apart from A[2,2]

## Principal Components

In [15]:
# First pair each eigen value with its corresponding eigen vector

eig_pairs = [(np.abs(lambdas[i]),vs[:,i]) for i in range(len(lambdas))]

eig_pairs.sort(key=lambda x:x[0], reverse=True)

# Print principal components in decreasing order
for i in eig_pairs:
    print(i[0])

11.482556772137679
6.894636210318462
8.881784197001252e-16


In [16]:
# First pair each eigen value with its corresponding eigen vector

eig_pairs = [(np.abs(lambdas_sc[i]),vs_sc[:,i]) for i in range(len(lambdas_sc))]

eig_pairs.sort(key=lambda x:x[0], reverse=True)

# Print principal components in decreasing order
for i in eig_pairs:
    print(i[0])

116.69054415286867
66.64278918046463
1.4210854715202004e-14
