In [3]:
import numpy as np

# Arrays

In this section we look at how to initialize numpy arrays from regular python lists and ranges and also how to convert them back to python lists. The statement `np.array(python_list)` creates a numpy array from a python list. We can also check properties of the list using numpy functions such as `size()`, `ndim` and `shape` which return the number of elements in the array, the number of dimensions and the dimensions of the array respectively

In [4]:
data = [1,2,3,4,5,6]
arr1 = np.array(data)
print(arr1)
data2 = [range(1,5),range(1,5)]
arr2 = np.array(data2)
print(arr2)
l_arr2 = arr2.tolist()
print(l_arr2)

[1 2 3 4 5 6]
[[1 2 3 4]
 [1 2 3 4]]
[[1, 2, 3, 4], [1, 2, 3, 4]]


In [5]:
print(arr2.shape)

(2, 4)


In [7]:
d = [*range(1,5)]
print(d)

[1, 2, 3, 4]


## Special Arrays

Special arrays like `np.zeros((dims))` will create an ndim array filled with zeros. `np.oness((dims))` will create an ndim array populated with ones. `linspace(0,1,5)` will create a set of 5 points on a linear scale between 0 and 1. `logspace(0,3,4)` will create a set of 4 points on a log scale between 10^0 and 10^3

In [14]:
print("zeros, 10")
print(np.zeros(10))
print("\nzeros, 3 by 6")
print(np.zeros((3, 6)))
print("\nones 10")
print(np.ones(10))
print("\nlinspace 0,1,5: 5 points on linear scale between 0 and 1")
print(np.linspace(0,1,5))
print("\nlogspace 0,3,4: 4 points on log scale between 10^0 and 10^3")
print(np.logspace(0,3,4))

zeros, 10
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

zeros, 3 by 6
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

ones 10
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

linspace 0,1,5: 5 points on linear scale between 0 and 1
[0.   0.25 0.5  0.75 1.  ]

logspace 0,3,4: 4 points on log scale between 10^0 and 10^3
[   1.   10.  100. 1000.]


## Arange

Builds a numpy array composed of a range of integers

In [17]:
int_array = np.arange(5)
int_array
float_array = int_array.astype(float)
print(f"float array: {float_array}")
print

float array: [0. 1. 2. 3. 4.]


In [21]:
print(arr2.dtype)
print(float_array.dtype)
print(type(float_array))
print(arr2.ndim)
print(arr2.ndim)
print(arr2.shape)

int64
float64
<class 'numpy.ndarray'>
2
2
(2, 4)


In [22]:
# Total number of elements in an np array
print(arr2.size)

# Size of 1st dimension or axis
print(len(arr2))

8
2


## Reshaping Arrays

`np_array.reshape(x,y)` will create a new array from `np_array` with the shape `(x,y)`. The product`x*y` must be equal to `np_array.size()`. `np_array.T` will create a transpose of `np_array`. `np_array.flatten` will create a one dimensional array from `np_array`. `np_array.ravel()` performs the same function

In [23]:
init_arr = np.arange(10,dtype=float)
rs_arr = init_arr.reshape(2,5)
rs_arr2 = init_arr.reshape(5,2)
print(rs_arr)
print(rs_arr2)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [36]:
a = np.array([0,1,2,3])
print(a.shape)
print(a.ndim)
a_col = a[np.newaxis,:]
print(a_col)
print(a_col.shape)
print(a_col.ndim)

(4,)
1
[[0 1 2 3]]
(1, 4)
2


In [37]:
a_tran = a_col.T
a_tran

array([[0],
       [1],
       [2],
       [3]])

In [38]:
flat = arr2.flatten()
flat

array([1, 2, 3, 4, 1, 2, 3, 4])

In [40]:
flat2 = arr2.ravel()
flat2

array([1, 2, 3, 4, 1, 2, 3, 4])

In [45]:
arr = np.array([[33., 1., 2.,3. ,4.],[5., 6., 7., 8., 9.]])
print(arr)

[[33.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


### Stacking arrays

Stacking offers a method of concatenating arrays. `np.stack(array1,array2)` builds a numpy array by making a row out of array1 and array2 and then joining those rows together. `np.hstack(a,b)` creates an n by 1 array where n is the combined number of elements of a and b. 

In [46]:
a = np.array([0,1])
b = np.array([2,3])
ab=np.stack((a,b))
ab

array([[0, 1],
       [2, 3]])

In [47]:
ab = np.hstack((a,b))
ab

array([0, 1, 2, 3])

In [49]:
ab = np.vstack((a,b))
ab

array([[0, 1],
       [2, 3]])

## Selection

`np_array[x,y]` returns the element at location row=x, col=y of the `np_array`

In [53]:
arr = np.arange(10,dtype=float).reshape((2,5))
print(arr[0])
print(arr[0,3])
print(arr[0][3])

[0. 1. 2. 3. 4.]
3.0
3.0


### Slicing

Allows the user to select a subset of the array

In [64]:
print("\nrow 0",arr[0,:])
print("\ncol 0",arr[:,0])
print("\ncols 0-2 without 2\n",arr[:,:2])
print("\ncols 2 to end \n",arr[:,2:])
print("\ncols between 1 and 4, 1 included 4 excluded \n",arr[:,1:4])


row 0 [0. 1. 2. 3. 4.]

col 0 [0. 5.]

cols 0-2 without 2
 [[0. 1.]
 [5. 6.]]

cols 2 to end 
 [[2. 3. 4.]
 [7. 8. 9.]]

cols between 1 and 4, 1 included 4 excluded 
 [[1. 2. 3.]
 [6. 7. 8.]]


### Fancy Indexing

In [68]:
arr2 = arr[:,[1,2,3]]
print(arr2)
arr2[0,0]=44
print(arr2,"\n",arr)

[[1. 2. 3.]
 [6. 7. 8.]]
[[44.  2.  3.]
 [ 6.  7.  8.]] 
 [[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [73]:
a = np.arange(0,10)
a2 = a>5
print(a2)
print(a[a2])
a[a<5]=0
print(a)

[False False False False False False  True  True  True  True]
[6 7 8 9]
[0 0 0 0 0 5 6 7 8 9]


### Boolean Indexing

In [84]:
n = np.array(['Bob','Joe','Will','Bob'])
n=='Bob'
print(n[n!='Bob'])
print(n[(n=='Bob') | (n=='Will')])
names[n != 'Bob']='Joe'
print(np.unique(n))

['Joe' 'Will']
['Bob' 'Will' 'Bob']
['Bob' 'Joe']


## Vectorized Ops

In [81]:
nums = np.arange(5)
print(nums*10)
nums = np.sqrt(nums)
print(np.ceil(nums))
print(np.isnan(nums))
nums = nums + np.arange(5)
print(nums)
np.maximum(nums, np.array([1,-2,3,-4,5]))

[ 0 10 20 30 40]
[0. 1. 2. 2. 2.]
[False False False False False]
[0.         2.         3.41421356 4.73205081 6.        ]


array([1.        , 2.        , 3.41421356, 4.73205081, 6.        ])

### Euclidean Distance

In [82]:
vec1 = np.random.randn(10)
vec2 = np.random.randn(10)
dist = np.sqrt(np.sum((vec1-vec2)**2))
print(dist)

3.773937861396542


# Exercise

In [115]:
X = np.random.randn(4,2)
print(X)

[[-1.12069474 -0.32445232]
 [-0.22377878  0.20347834]
 [ 1.41246264  0.88253277]
 [-0.64178833  0.66937819]]


In [116]:
def standardize(X):
    mean = np.mean(X,axis=0)
    std = np.std(X,axis=0)
    standardized = (X-mean)/std
    return standardized

In [117]:
standardized_x = standardize(X)
print(standardized_x)

[[-1.02574715 -1.46978187]
 [-0.08431583 -0.3323468 ]
 [ 1.63313485  1.13068681]
 [-0.52307186  0.67144187]]
